### ISSUE TITLE
No longer in the marketplace

### ISSUE THREAD

**Issue by polyglotdev** [IronLu233/vscode-color-exchange#2]
I was wondering why this extension was pulled from the marketplace? Are you needing help with maintaining because I would love to help.

**Comment by Yzrsah** [comment]
It was removed because of the bug "Initializing JS/TS Language Features" forever

https://github.com/IronLu233/vscode-color-exchange/issues/1

**Comment by polyglotdev** [comment]
Could I maybe work on it and see if I can help?

**Comment by IronLu233** [comment]
That’s very good. To be honest, I don’t konw how to quickly fix this issue. Pr is welcome.


开 2019年2月22日 在 上午9:57:06, Dominique Hallan (notifications@github.com) 写到:

Could I maybe work on it and see if I can help?

**Comment by polyglotdev** [comment]
I will jump on it.
